name: build

on: [push, pull_request]

jobs:

  linux:
    timeout-minutes: 5

    strategy:
      matrix:
        compiler: [g++, clang++]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Compile tests
      working-directory: build
      env:
        CXX: ${{ matrix.compiler }}
      run: |
        cmake -DBUILD_TESTING=ON -DBUILD_LIB=ON ..
        make -j4
    - name: Run tests
      working-directory: build
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: ctest --timeout 5 -C Debug -j4

  windows:
    timeout-minutes: 5

    strategy:
      matrix:
        os: [windows-latest, windows-2016]
        include:
          - os: windows-latest
            generator: Visual Studio 16 2019
          - os: windows-2016
            generator: Visual Studio 15 2017

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Compile tests
      working-directory: build
      run: |
        cmake -DBUILD_TESTING=ON -DBUILD_LIB=ON -DCMAKE_CXX_FLAGS=/W1 -G"${{ matrix.generator }}" ..
        cmake --build . -j 4
    - name: Run tests
      working-directory: build
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: ctest --timeout 5 -C Debug -j4

  macos:
    timeout-minutes: 5
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Compile tests
      working-directory: build
      run: |
        cmake -DBUILD_TESTING=ON -DBUILD_LIB=ON ..
        make -j4
    - name: Run tests
      working-directory: build
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: ctest --timeout 5 -C Debug -j4
